# Generated by Django 5.0.4 on 2024-06-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0002_register_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Total_price', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
