# Generated by Django 5.0.4 on 2024-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0003_cart_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='placeorder_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('bill', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cart_db',
            old_name='Total_price',
            new_name='total_price',
        ),
    ]
