# Generated by Django 5.0.4 on 2024-06-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0004_placeorder_db_rename_total_price_cart_db_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder_db',
            name='total_price',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
