# Generated by Django 5.0.4 on 2024-05-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laModa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductCategory', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='ProductImage')),
            ],
        ),
    ]
